from .dataset_loader import Cancer1Dataset
from .dataset_loader import Cancer2Dataset
from .dataset_loader import Cancer3Dataset
from .dataset_loader import Diabetes1Dataset
from .dataset_loader import Diabetes2Dataset
from .dataset_loader import Diabetes3Dataset
from .dataset_loader import Glass1Dataset
from .dataset_loader import Glass2Dataset
from .dataset_loader import Glass3Dataset
from .dataset_loader import Card1Dataset
from .dataset_loader import Card2Dataset
from .dataset_loader import Card3Dataset
from .dataset_loader import Flare1Dataset
from .dataset_loader import Flare2Dataset
from .dataset_loader import Flare3Dataset
from .dataset_loader import Gene1Dataset
from .dataset_loader import Gene2Dataset
from .dataset_loader import Gene3Dataset
from .dataset_loader import Heart1Dataset
from .dataset_loader import Heart2Dataset
from .dataset_loader import Heart3Dataset
from .dataset_loader import Horse1Dataset
from .dataset_loader import Horse2Dataset
from .dataset_loader import Horse3Dataset
from .dataset_loader import Mushroom1Dataset
from .dataset_loader import Mushroom2Dataset
from .dataset_loader import Mushroom3Dataset
from .dataset_loader import Soybean1Dataset
from .dataset_loader import Soybean2Dataset
from .dataset_loader import Soybean3Dataset
from .dataset_loader import Thyroid1Dataset
from .dataset_loader import Thyroid2Dataset
from .dataset_loader import Thyroid3Dataset
